export const recipes = {
  starter: {
    soup: {
      name: 'Chestnut & Panchetta Soup',
      ingredients: [
        '2 packs of panchetta',
        '3 Tbsp unsalted butter',
        '1.5 shallot large roughly chopped',
        '1.5 carrot medium, roughly chopped',
        '1 large leek, cleaned thoroughly, roughly chopped',
        '2 stalk celery roughly chopped',
        '3 cloves garlic',
        '9 cups chicken stock (5 stock cubes)',
        '4 cup (22.5 oz) roasted chestnuts',
        '2 bay leaf',
        '2 sprig thyme',
        '½ cup heavy cream',
        '¾ tsp nutmeg - freshly grated',
        'kosher salt',
        'freshly ground black pepper',
      ],
      method: [
        'In a large saucepan over medium heat, cook panchetta until rendered and crisp, 8 to 10 minutes. Transfer bacon to a paper towel-lined plate and set aside to cool.',
        'Pour off all but 1 teaspoon of the fat. In the same saucepan, add butter, shallot, carrot, leek, celery and garlic; cook, stirring occasionally, until vegetables are soft, 5-7 minutes.',
        'Add stock, chestnuts, panchetta, bay leaf, and thyme; bring to a boil.',
        'Reduce heat to medium; cook, slightly covered, until chestnuts are very tender, about 30 minutes. Remove from heat and let cool slightly.',
        'Discard bay leaves and thyme. Working in batches, carefully purée soup in a blender until smooth.',
        'Stir in cream, nutmeg, salt, and pepper to taste; cook until soup is slightly thick, about 5 minutes more, addding more broth to desired thickness.',
      ],
    },
    bread: {
      name: 'Sage & Parmesan Bread',
      ingredients: [
        '2 ½ cups all-purpose flour',
        '1 cup grated Parmesan cheese',
        '2 tablespoons sugar',
        '3 teaspoons baking powder',
        '1 tablespoon chopped fresh sage',
        '1 teaspoon salt',
        '1 ½ cups beer',
        '¼ cup melted butter, divided',
      ],
      method: [
        'Preheat oven to 190°. In a small bowl, whisk the first 6 ingredients. Add beer and 3 tablespoons melted butter; stir just until moistened.',
        'Transfer to a greased 8x4-in. loaf pan. Drizzle with remaining butter. Bake 45-50 minutes or until a toothpick inserted in center comes out clean. Cool in pan 5 minutes before removing to a wire rack to cool.',
      ],
    },
  },
  main: {
    ham: {
      name: 'Cola Ham',
      ingredients: [
        '2.5kg unsmoked boneless gammon joint',
        '3.33l full fat coke',
        '2 carrot peeled and chopped',
        '2 onion peeled and quartered',
        '2 stick celery chopped',
        '2 cinnamon stick',
        '1 Tbsp peppercorns',
        '2 bay leaf',
        '250ml maple syrup',
        '3 ⅓ Tbsp wholegrain mustard',
        '3 ⅓ Tbsp red wine vinegar',
        'pinch ground cloves',
      ],
      method: [
        'Set your slow cooker to medium. Place the gammon joint in and cover with the cola. Add the carrot, onion, celery, cinnamon stick, peppercorns and bay leaves.',
        'Cook for 5½ hrs on low until the gammon is tender but still holding its shape, topping up with boiling water if necessary to keep the gammon fully covered.',
        'Carefully pour the liquid away, then let the ham cool a little while you heat the oven to fan 170C. Lift the ham into a roasting tin, then cut away the skin leaving behind an even layer of fat. Score the fat all over in a criss-cross pattern.',
        'Mix the maple syrup, mustard, vinegar and ground cloves or five-spice in a jug. Pour half over the fat, roast for 15 mins, then pour over the rest and return to the oven for another 30 mins.',
        'Remove from the oven and allow to rest for 10 mins, then spoon more glaze over the top. Can be roasted on the day or up to two days ahead and served cold.',
      ],
    },
    goose: {
      name: 'Roast Goose',
      ingredients: [
        '4-5.5kg fresh goose',
        '4 lemons',
        '3 limes',
        '1 tsp Chinese five-spice powder',
        'small handful each of parsley sprigs, thyme and sage, plus extra for garnishing',
        'a little olive oil, for browning, optional',
        '3 tbsp clear honey',
        '1 tbsp thyme leaves',
      ],
      method: [
        'Calculate the cooking time: cook for 10 mins at fan 220C, then reduce to fan 170C and cook for 32 mins per kg for more well done, plus 30 mins resting.',
        'If the goose is ready-trussed, then loosen the string and pull out the legs and wings a little - this helps the bird cook better.',
        'Check the inside of the bird and remove any giblets or pads of fat. Using the tip of a sharp knife, lightly score the breast and leg skin in a criss-cross. This helps the fat to render down more quickly during roasting.',
        'Grate the zest from 4 lemons and 3 limes. Mix with 2 tsp fine sea salt, 1 tsp Chinese five-spice powder and pepper, to taste.',
        'Season the cavity of the goose generously with salt, then rub the citrus mix well into the skin and sprinkle some inside the cavity.',
        'Stuff the zested fruit and a small handful of parsley, thyme and sage sprigs inside the bird and set aside for at least 15 mins. Can be done up to a day ahead and kept refrigerated.',
        'Heat oven to fan 220C.',
        'If you want to give the bird a nice golden skin, brown in a large frying pan (or a heavy-based roasting tin), using a couple of tbsp olive oil. Holding the bird by the legs (you may like to use an oven glove), press it down on the breasts to brown.',
        'Once browned, place the bird in the roasting tin. Drizzle with 3 tbsp clear honey and sprinkle with 1 tbsp thyme leaves.',
        'Roast for the calculated time, turning the heat down after 10 mins to fan 170C. Cover the goose with foil if it is starting to brown too much.',
        'Every 30 mins or so, baste the bird with the pan juices, then pour off the fat through a sieve into a large heatproof bowl. You will end up with at least a litre of luscious fat - save this for the potatoes and other veg.',
        'At the end of the cooking time, leave to rest for at least 30 mins, covered loosely with foil. The bird will not go cold, but will be moist and much easier to carve.',
      ],
    },
    potato: {
      name: 'Roast Potato',
      ingredients: [
        '14 Maris Piper Potatoes peeled and cut to serving size',
        '2 cloves garlic heads cut off',
        'bag of thyme',
        'bag of rosemarie',
        'handful of peppercorns',
        '2 jars of Goose Fat',
        'table salt',
        'ground pepper',
      ],
      method: [
        'Infuse goose fat with the garlic, thyme and rosemarie. Frying until fragrant.',
        'Boil the cut potatoes for 10 minutes, until a knife cleanly goes through it.',
        'Preheat the oven to 200°',
        'Let the potatoes cool, toss with salt, pepper and oil then lay out on baking tray.',
        'Cook the potatoes for 45 minutes, turning and basting every 15 minutes.',
        'Leave to cool for 5 minutes before serving.',
      ],
    },
    roots: {
      name: 'Roast Carrots & Parsnips',
      ingredients: [
        '4 Large Carrots, peeled but not topped and tailed',
        '4 Large Parsnips, peeled but not topped and tailed',
        '1 bag of fresh thyme, roughly chopped',
        '1 bag of fresh rosemary, roughly chopped',
        'ground salt',
        'ground pepper',
        '3 Tub goose fat',
        'Runny honey',
      ],
      method: [
        'Boil the carrots and parsnips whole, for 10 minutes.',
        'Strain and let cool.',
        'Preheat the oven to 200°.',
        'Top and tail and quarter the veg.',
        'Toss the veg in the thyme, rosemary, salt, pepper and goose fat.',
        'Roast for 30 minutes.',
        'Coat with honey then roast for 20 more minutes.',
        'Let dry on a rack then serve.',
      ],
    },
    stuffing: {
      name: 'Stuffing',
      ingredients: [],
      method: [],
    },
    pigs: {
      name: 'Pigs in Blankets',
      ingredients: [],
      method: [],
    },
    sprouts: {
      name: 'Brussel Sprouts & Chestnuts',
      ingredients: [],
      method: [],
    },
  },
  dessert: {
    christmas: {
      name: 'Christmas Pudding',
      ingredients: [],
      method: [],
    },
    toffee: {
      name: 'Sticky Toffee Pudding',
      ingredients: [],
      method: [],
    },
  },
};
